class ConfigConst:
    PG_WAREHOUSE_CONNECTION = "PG_WAREHOUSE_CONNECTION"
    PG_WAREHOUSE_CONNECTION_CLOUD = "PG_WAREHOUSE_CONNECTION_CLOUD"
    PG_ORIGIN_BONUS_SYSTEM_CONNECTION = "PG_ORIGIN_BONUS_SYSTEM_CONNECTION"

    MONGO_DB_CERTIFICATE_PATH = 'MONGO_DB_CERTIFICATE_PATH'
    MONGO_DB_USER = 'MONGO_DB_USER'
    MONGO_DB_PASSWORD = 'MONGO_DB_PASSWORD'
    MONGO_DB_REPLICA_SET = 'MONGO_DB_REPLICA_SET'
    MONGO_DB_DATABASE_NAME = 'MONGO_DB_DATABASE_NAME'
    MONGO_DB_HOSTS = 'MONGO_DB_HOSTS'

    PG_ORIGIN_DATABASE_NAME = "PG_ORIGIN_DATABASE_NAME"
    PG_ORIGIN_HOST = "PG_ORIGIN_HOST"
    PG_ORIGIN_PASSWORD = "PG_ORIGIN_PASSWORD"
    PG_ORIGIN_PORT = "PG_ORIGIN_PORT"
    PG_ORIGIN_USER = "PG_ORIGIN_USER"
